### ISSUE TITLE
More yealds

### ISSUE THREAD

**Issue by DickBaker** [CodeMazeBlog/async-enumerable-yield-csharp#2]
Thanks for just fixing my Issue #1, but there are many others e.g. at https://github.com/CodeMazeBlog/async-enumerable-yield-csharp/tree/main/async-streams
Thanks, Dick

**Comment by CodeMazeBlog** [comment]
Yeah, that's the commit message, we won't be changing that, unfortunately. It just slipped by, and it's not that big of a deal.
Thanks for helping us though, we appreciate your effort.

**Comment by DickBaker** [comment]
Yeah I get that commit message (s) were mis-spelled and they still show, but reading those texts detracts from CM's tech credibility and would be so easy to post a new commit after "touching" appropriate source files. Consider it an early form of Spring-cleaning!

**Comment by CodeMazeBlog** [comment]
Yes, we'll probably do that if we decide to edit the article now. But since we're working on many new articles and authors are very busy, this might happen a bit later on.

**Comment by DickBaker** [comment]
OK, understood that you're busy with new Ultimate vnext shiny stuff. I will probably post another comment [on the original article] as a new Issue here as your [https://code-maze.com/contact/](url) is limited and doesn't have MD formatting. Happy Coding!
